# Prettier configuration for Weekly Recipes

# Print width - line length that the printer will wrap on
printWidth: 100

# Tab width - number of spaces per indentation level
tabWidth: 2

# Use tabs instead of spaces
useTabs: false

# Semicolons - print semicolons at the ends of statements
semi: true

# Single quotes - use single quotes instead of double quotes
singleQuote: true

# Quote properties - only add quotes around object properties when necessary
quoteProps: 'as-needed'

# JSX quotes - use single quotes in JSX
jsxSingleQuote: true

# Trailing commas - print trailing commas when possible
trailingComma: 'es5'

# Bracket spacing - print spaces between brackets in object literals
bracketSpacing: true

# Bracket same line - put the > of a multi-line JSX element at the end of the last line
bracketSameLine: false

# Arrow function parentheses - omit parentheses when possible
arrowParens: 'avoid'

# Range - format only a segment of a file
rangeStart: 0
rangeEnd: Infinity

# Parser - which parser to use
# Auto-detected based on file extension

# File path - file path to use for config overrides
# Handled by CLI

# Require pragma - only format files that contain a special comment
requirePragma: false

# Insert pragma - insert a special comment at the top of files
insertPragma: false

# Prose wrap - how to wrap prose (markdown)
proseWrap: 'preserve'

# HTML whitespace sensitivity
htmlWhitespaceSensitivity: 'css'

# Vue files script and style tags indentation
vueIndentScriptAndStyle: false

# End of line - line ending style
endOfLine: 'lf'

# Embedded language formatting
embeddedLanguageFormatting: 'auto'

# Single attribute per line in HTML/Vue/JSX
singleAttributePerLine: false
